example:
  property: "I AM A DEV PROPERTY OVERRIDE"

spring:
  datasource:
    url: "jdbc:postgresql://database:5432/logistic_dev"
    username: "postgres_dev"
    password: "c3448c4285887fc3bfa092df9f6e2e57faa21cf533fd1219467d8ed7a9efdf74"
    dbcp2:
      test-while-idle: "true"
      validation-query: "SELECT 1"
    driver-class-name: "org.postgresql.Driver"

  sql:
    init:
      continue-on-error: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"